on: [push, pull_request]
name: CI Checks
jobs:
  check:
    name: Check and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv6m-none-eabi
      - run: "cargo check --all"
      - run: "cargo fmt -- --check"
      - run: "cargo clippy -- -Dwarnings"
